#server
server.host = 0.0.0.0
server.port = 8080
server.io_threads = 2
server.max_body_size = 1048576

#worker
worker_pool.threads = 4

#rule
rule.file = config/rules.dsl

#mysql
mysql.host = 127.0.0.1
mysql.port = 3306
mysql.user = admin
mysql.password = 123
mysql.database = aegisflow
mysql.charset = utf8mb4
mysql.connect_timeout_sec = 3
mysql.read_timeout_sec = 3
mysql.write_timeout_sec = 3

#redis
redis.host = 127.0.0.1
redis.port = 6379
redis.password = 123456
redis.timeout_ms = 50

#blacklist
blacklist.bloom_bits = 16777216
blacklist.bloom_hashes = 7
blacklist.cache_capacity = 100000
blacklist.negative_ttl_ms = 30000
blacklist.positive_ttl_ms = 60000

#log
log.level = INFO
log.file = logs/log.log