syntax = "proto3";

package aegisflow.v1;

// 事件类型
enum EventType {
    // 未知事件， 默认
    EVENT_TYPE_UNKNOWN = 0;
    // 登录
    LOGIN = 1;
    // 支付
    PAY = 2;
    // 点击
    CLICK = 3;
    // 发布
    POST = 4;
}

enum EventResult {
    EVENT_RESULT_UNKNOWN = 0;
    SUCCESS = 1;
    FAIL = 2;
}

message Event {
    uint64 event_id = 1;
    uint64 timestamp_ms = 2;

    string user_id = 3;
    string ip = 4;
    string device_id = 5;
    string scene = 6;

    EventType type = 7;
    EventResult result = 8;
}

message ReportEventRequest {
    Event event = 1;
}

message BatchReportRequest {
    repeated Event events = 1;
}